AppWebBA-Django/AppWebBA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('BuenosAiresApiRest/', include('apirest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppWebBA-Django/core/urls.py
from django import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from .views import (
    home, administrar_productos, tienda, ficha, iniciar_sesion,
    registrar_usuario, cerrar_sesion, perfil_usuario, iniciar_pago,
    pago_exitoso, obtener_solicitudes_de_servicio, mis_compras,
     facturas, ingresar_solicitud_servicio, aceptar_solicitud,
    modificar_solicitud, cerrar_solicitud
)

urlpatterns = [
    # General URLs
    path('', home, name="home"),
    path('iniciar_sesion/', iniciar_sesion, name="iniciar_sesion"),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
    path('registrar_usuario/', registrar_usuario, name="registrar_usuario"),
    path('perfil_usuario/', perfil_usuario, name="perfil_usuario"),
    
    # Password management
    path('cambiar_password/', 
         auth_views.PasswordChangeView.as_view(
             template_name='core/cambiar_password.html',
             success_url='/password_cambiada'
         ),
         name='cambiar_password'),
    path('password_cambiada/',
         TemplateView.as_view(template_name='core/password_cambiada.html'),
         name='password_cambiada'),

    # Shop related
    path('tienda/', tienda, name="tienda"),
    path('ficha/<int:id>', ficha, name="ficha"),
    path('iniciar_pago/<int:id>', iniciar_pago, name="iniciar_pago"),
    path('pago_exitoso/', pago_exitoso, name="pago_exitoso"),
    
    # Product management
    path('administrar_productos/<action>/<id>',
         administrar_productos,
         name="administrar_productos"),

    # Cliente views
    path('mis-compras/', mis_compras, name='mis_compras'),
#     path('mis-solicitudes/', mis_solicitudes, name='mis_solicitudes'),
    
    # Técnico and Administrador views
    path('solicitudes/', obtener_solicitudes_de_servicio, 
         name='obtener_solicitudes'),  # Short name for template usage
    path('solicitudes-servicio/', obtener_solicitudes_de_servicio, 
         name='obtener_solicitudes_de_servicio'),  # Original name

     path('aceptar_solicitud/<int:nrosol>/', aceptar_solicitud, name='aceptar_solicitud'),
     path('modificar_solicitud/<int:nrosol>/', modificar_solicitud, name='modificar_solicitud'),
     path('cerrar_solicitud/<int:nrosol>/', cerrar_solicitud, name='cerrar_solicitud'),
    
    # Administrador views
    path('facturas/', facturas, name='facturas'),  # For admin to see all invoices
    
    path('ingresar_solicitud_servicio/', ingresar_solicitud_servicio, name='ingresar_solicitud_servicio'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppWebBA-Django/core/models.py
from django.db import models
from django.contrib.auth.models import User

class PerfilUsuario(models.Model):
    TIPOUSU_CHOICES = [
        ('Cliente', 'Cliente'),
        ('Técnico', 'Técnico'),
        ('Bodeguero', 'Bodeguero'),
        ('Vendedor', 'Vendedor'),
        ('Administrador', 'Administrador'),
        ('Superusuario', 'Superusuario'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut = models.CharField(primary_key=True, max_length=20)
    tipousu = models.CharField(choices=TIPOUSU_CHOICES, max_length=50, null=False, blank=False)
    dirusu = models.CharField(max_length=300, null=False, blank=False)
    
    class Meta:
        db_table = 'PerfilUsuario'

    def __str__(self):
        return f'{self.rut} - {self.user.first_name} {self.user.last_name}'

class Producto(models.Model):
    idprod = models.IntegerField(primary_key=True, verbose_name='ID Prod')
    nomprod = models.CharField(max_length=100, null=False, blank=False, verbose_name='Nombre')
    descprod = models.CharField(max_length=300, null=False, blank=False, verbose_name='Descripción')
    precio = models.IntegerField(null=False, blank=False, verbose_name='Precio')
    imagen = models.ImageField(upload_to="images/", default="sinfoto.jpg", null=False, blank=False, verbose_name="Imagen")

    class Meta:
        db_table = 'Producto'
    
    def __str__(self):
        return f'{self.idprod} - {self.nomprod}'

class Factura(models.Model):
    nrofac = models.IntegerField(primary_key=True)
    rutcli = models.ForeignKey(PerfilUsuario, models.DO_NOTHING, db_column='rutcli', null=False, blank=False)
    idprod = models.ForeignKey(Producto, models.DO_NOTHING, db_column='idprod', null=False, blank=False)
    fechafac = models.DateField(null=False, blank=False)
    descfac = models.CharField(max_length=300, null=False, blank=False)
    monto = models.IntegerField(null=False, blank=False)
    # guiadespacho = models.ForeignKey(GuiaDespacho, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = 'Factura'
    
    def __str__(self):
        clave = f'F-{self.nrofac}'
        solsers = SolicitudServicio.objects.raw(f'SELECT * FROM SolicitudServicio WHERE nrofac={self.nrofac}')
        if len(solsers) > 0:
            clave += f' SS-{solsers[0].nrosol}-{solsers[0].tiposol[:3].upper()}'
        stocks = StockProducto.objects.raw(f'SELECT * FROM StockProducto WHERE nrofac={self.nrofac}')
        if len(stocks) > 0:
            clave += f' IDS-{stocks[0].idstock}'
        else:
            clave += f' **********'
        return f'{clave} - {self.rutcli.user.first_name[0]}. {self.rutcli.user.last_name} - {self.idprod.nomprod}'

class SolicitudServicio(models.Model):
    TIPOSOL_CHOICES = [
        ('Instalación', 'Instalación'),
        ('Mantención', 'Mantención'),
        ('Reparación', 'Reparación'),
    ]
    ESTADOSOL_CHOICES = [
        ('Aceptada', 'Aceptada'),
        ('Modificada', 'Modificada'),
        ('Cerrada', 'Cerrada'),
        ('Anulada', 'Anulada'),
    ]
    nrosol = models.IntegerField(primary_key=True)
    nrofac = models.ForeignKey(Factura, models.DO_NOTHING, db_column='nrofac', null=False, blank=False)
    tiposol = models.CharField(choices=TIPOSOL_CHOICES, max_length=50, null=False, blank=False)
    fechavisita = models.DateField(null=False, blank=False)
    ruttec = models.ForeignKey(PerfilUsuario, models.DO_NOTHING, db_column='ruttec', null=False, blank=False)
    descsol = models.CharField(max_length=200, null=False, blank=False)
    estadosol = models.CharField(choices=ESTADOSOL_CHOICES, max_length=50, null=False, blank=False)

    class Meta:
        db_table = 'SolicitudServicio'
    
    def __str__(self):
        clave = f'{self.nrosol} - {self.tiposol} - Técnico ({self.ruttec.user.first_name} {self.ruttec.user.last_name})'
        clave += f' - Cliente ({self.nrofac.rutcli.user.first_name} {self.nrofac.rutcli.user.last_name}) Factura ({self.nrofac})'
        return clave

class GuiaDespacho(models.Model):
    ESTADOGD_CHOICES = [
        ('En bodega', 'En bodega'),
        ('Despachado', 'Despachado'),
        ('Entregado', 'Entregado'),
    ]
    nrogd = models.IntegerField(primary_key=True)
    nrofac = models.ForeignKey(Factura, models.DO_NOTHING, db_column='nrofac', null=False, blank=False)
    idprod = models.ForeignKey(Producto, models.DO_NOTHING, db_column='idprod', null=False, blank=False)
    estadogd = models.CharField(choices=ESTADOGD_CHOICES, max_length=50, null=False, blank=False)

    class Meta:
        db_table = 'GuiaDespacho'

    def __str__(self):
        clave = f'{self.nrogd} - Cliente ({self.nrofac.rutcli.user.first_name} {self.nrofac.rutcli.user.last_name})'
        clave += f' -  Factura ({self.nrofac}, {self.nrofac.idprod.nomprod})'
        return clave

class StockProducto(models.Model):
    idstock = models.IntegerField(primary_key=True)
    idprod = models.ForeignKey(Producto, models.DO_NOTHING, db_column='idprod', null=False, blank=False)
    nrofac = models.ForeignKey(Factura, models.DO_NOTHING, db_column='nrofac', blank=True, null=True)
    cantidad = models.IntegerField(null=False, blank=False, default=1)

    class Meta:
        db_table = 'StockProducto'
    
    def __str__(self):
        clave = ''
        if self.nrofac is not None:
            cliente = f'Cliente ({self.nrofac.rutcli.user.first_name} {self.nrofac.rutcli.user.last_name})'
            factura = f'Factura ({self.nrofac}, {self.nrofac.idprod.nomprod})'
            clave = f'{self.idstock} - {cliente} - {factura}'
        else:
            clave = f'{self.idstock} - Producto en bodega'
        return clave

class AnwoStockProducto(models.Model):
    RESERVADO_CHOICES = [
        ('S', 'Reservado'),
        ('N', 'No reservado'),
    ]
    nroserieanwo = models.CharField(primary_key=True, max_length=100)
    nomprodanwo = models.CharField(max_length=100, null=False, blank=False)
    precioanwo = models.IntegerField(null=False, blank=False)
    reservado = models.CharField(choices=RESERVADO_CHOICES, max_length=1, null=False, blank=False)

    class Meta:
        db_table = 'AnwoStockProducto'
        
    def __str__(self):
        return f'{self.nroserieanwo} - {self.nomprodanwo}'

AppWebBA-Django/core/forms.py
from django import forms
from django.forms import ModelForm, fields, Form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Producto, PerfilUsuario

class ProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = ['idprod', 'nomprod', 'descprod', 'precio', 'imagen']

class IniciarSesionForm(Form):
    username = forms.CharField(widget=forms.TextInput(), label="Correo")
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña")
    class Meta:
        fields = ['username', 'password']

class RegistrarUsuarioForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True, label='Nombre')
    last_name = forms.CharField(max_length=100, required=True, label='Apellido')
    email = forms.EmailField(required=True, label='Email')
    rut = forms.CharField(max_length=12, required=True, label='RUT')
    dirusu = forms.CharField(max_length=200, required=True, label='Dirección')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'rut', 'dirusu')

class PerfilUsuarioForm(Form):
    first_name = forms.CharField(max_length=150, required=True, label="Nombres")
    last_name = forms.CharField(max_length=150, required=True, label="Apellidos")
    email = forms.CharField(max_length=254, required=True, label="Correo")
    rut = forms.CharField(max_length=20, required=False, label="Rut")
    tipousu = forms.CharField(
        max_length=50,
        required=True,
        label="Tipo de usuario",
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )
    dirusu = forms.CharField(max_length=300, required=False, label="Dirección")

    class Meta:
        fields = '__all__'

class SolicitudServicioForm(forms.Form):
    TIPO_SOLICITUD_CHOICES = [
        ('Mantención', 'Mantención'),
        ('Reparación', 'Reparación'),
    ]
    tipo_solicitud = forms.ChoiceField(choices=TIPO_SOLICITUD_CHOICES, label="Tipo de Solicitud")
    descripcion = forms.CharField(widget=forms.Textarea, label="Descripción")
    fecha_sugerida = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label="Fecha Sugerida")
    hora_sugerida = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}), label="Hora Sugerida")

AppWebBA-Django/core/templates/core/Ingresar_solicitud_servicio.html
{% extends 'core/base.html' %}

{% block title %}
    <title>Ingresar Solicitud de Servicio</title>
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Ingresar una Solicitud de Servicio</h2>
    {% if error %}
        <div class="alert alert-danger">{{ error }}</div>
    {% endif %}
    {% if success %}
        <div class="alert alert-success">¡Su Solicitud de Servicio ha sido generada con éxito!</div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Precio del servicio</label>
            <div>
                <strong>$25.000</strong>
            </div>
        </div>
        <div class="mb-3">
            <label for="tipo_solicitud" class="form-label">Tipo de solicitud</label>
            <select name="tipo_solicitud" id="tipo_solicitud" class="form-select" required>
                <option value="Mantención">Mantención</option>
                <option value="Reparación">Reparación</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción</label>
            <textarea name="descripcion" id="descripcion" class="form-control" rows="3" required></textarea>
        </div>
        <div class="mb-3">
            <label for="fecha_visita" class="form-label">Fecha de la visita</label>
            <input type="date" name="fecha_visita" id="fecha_visita" class="form-control" required>
        </div>
        {% comment %} <div class="mb-3">
            <label for="hora_visita" class="form-label">Hora de la visita</label>
            <input type="time" name="hora_visita" id="hora_visita" class="form-control" required>
        </div> {% endcomment %}
        <button type="submit" class="btn btn-primary">Pagar</button>
    </form>
</div>
{% endblock %}

AppWebBA-Django/core/templates/core/administrar_productos.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'core/css/forms.css' %}" rel="stylesheet">
<link href="{% static 'core/css/administrar_productos.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="admin-productos-container">
    <h1 class="text-center text-primary fw-bold mb-4">Administrar Productos</h1>

    {% if form %}
    <form method="POST" enctype="multipart/form-data" id="formulario" class="formulario-pequeno">
        <div class="form-group">
            {% csrf_token %}
            {{ form.as_ul }}

            {% if action == 'upd' %}
            <script>
                $(document).ready(function () {
                    $('#id_patente').attr('readonly', true);
                });
            </script>
            {% endif %}
        </div>

        <div class="form-botones mt-4 d-flex flex-wrap gap-2 mb-3">
            <input type="submit" class="btn btn-primary" value="Guardar">
            <a class="btn btn-success" href="{% url 'administrar_productos' 'ins' -1 %}">Nuevo</a>
            {% if id != '-1' %}
            <a class="btn btn-danger" href="{% url 'administrar_productos' 'del' id %}">Eliminar</a>
            {% endif %}
            <a class="btn btn-secondary" href="{% url 'home' %}">Inicio</a>
        </div>

        {% if mesg %}
        <div id="form_message" class="alert alert-danger" role="alert">{{ mesg }}</div>
        {% endif %}
    </form>
    {% endif %}

    {% if list %}
    <div class="table-responsive">
        <table class="table table-hover align-middle text-center" id="tabla_datos">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Precio</th>
                    <th>Imagen</th>
                    <th class="titulo_boton">Editar</th>
                    <th class="titulo_boton">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in list %}
                <tr>
                    <td>{{ producto.idprod }}</td>
                    <td>{{ producto.nomprod }}</td>
                    <td>{{ producto.descprod }}</td>
                    <td>${{ producto.precio }}</td>
                    <td><img src="/media/{{ producto.imagen }}" class="mini_auto" alt="Producto"></td>
                    <td>
                        <a href="{% url 'administrar_productos' 'upd' producto.idprod %}" class="btn btn-outline-primary btn-sm">Editar</a>
                    </td>
                    <td>
                        <a href="{% url 'administrar_productos' 'del' producto.idprod %}" class="btn btn-outline-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

    <div class="text-center mt-4">
        <a href="http://127.0.0.1:8000/admin" class="btn btn-outline-info btn-sm me-2">Panel Django Admin</a>
        <a href="{% url 'home' %}" class="btn btn-outline-secondary btn-sm">Volver al Inicio</a>
    </div>
</div>
{% endblock %}

AppWebBA-Django/core/templates/core/cambiar_password.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'core/css/cambiar_password.css'%}" rel="stylesheet">
<style>
    .form-container {
        margin: 50px auto;
        padding: 30px;
        background-color: #ffffff;
        border-radius: 15px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        animation: fade-slide-in 0.8s ease-out forwards;
    }

    @keyframes fade-slide-in {
        from {
            opacity: 0;
            transform: translateY(30px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    input[type="text"],
    input[type="email"],
    input[type="password"],
    select,
    textarea {
        transition: all 0.3s ease;
        border: 1px solid #ccc;
        border-radius: 8px;
        padding: 10px;
        width: 100%;
    }

    input:focus,
    select:focus,
    textarea:focus {
        outline: none;
        border-color: #007bff;
        box-shadow: 0 0 8px rgba(0, 123, 255, 0.4);
        background-color: #f9f9ff;
    }

    label {
        font-weight: 500;
        font-size: 0.95rem;
        color: #333;
        margin-bottom: 5px;
        display: block;
    }

    .form-title {
        color: #004080;
        font-weight: bold;
        margin-bottom: 30px;
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container">
                <h2 class="form-title">Cambiar Contraseña</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center mt-3">
                        <button type="submit" class="btn btn-primary px-5">Cambiar Contraseña</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

AppWebBA-Django/core/templates/core/facturas.html
{% extends 'core/base.html' %}

{% block title %}
    <title>Mis Compras - Aires Acondicionados Buenos Aires</title>
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Mis Compras</h2>

    {% if facturas %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nº Factura</th>
                        <th>Cliente</th>
                        <th>Fecha</th>
                        <th>descripcion</th>
                        <th>Monto</th>
                        <th>Nro GB</th>
                        <th>Estado Guia</th>
                        <th>Nro SS</th>
                    </tr>
                </thead>
                <tbody>
                    {% for factura in facturas %}
                        <tr>
                            <td>{{ factura.nrofac }}</td>
                            <td>{{ factura.rutcli }}</td>
                            <td>{{ factura.fechafac }}</td>
                            <td>{{ factura.descfac }}</td>
                            <td>${{ factura.monto|floatformat:0 }}</td>
                            <td>
                                {% if factura.guiadespacho_set.all %}
                                    {% for guia in factura.guiadespacho_set.all %}
                                        {{ guia.nrogd }}
                                    {% empty %}
                                        -
                                    {% endfor %}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td>
                                {% if factura.guiadespacho_set.all %}
                                    {% for guia in factura.guiadespacho_set.all %}
                                        {{ guia.estadogd }}
                                    {% empty %}
                                        -
                                    {% endfor %}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td>
                                {% if factura.guiadespacho_set.all %}
                                    {% for guia in factura.guiadespacho_set.all %}
                                        {% with solicitudes=guia.nrofac.solicitudservicio_set.all %}
                                            {% if solicitudes %}
                                                {% for solicitud in solicitudes %}
                                                    {{ solicitud.nrosol }}
                                                {% empty %}
                                                    -
                                                {% endfor %}
                                            {% else %}
                                                -
                                            {% endif %}
                                        {% endwith %}
                                    {% empty %}
                                        -
                                    {% endfor %}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-info">
            No tienes compras registradas.
        </div>
    {% endif %}
</div>
{% endblock %}

{% block stylesheet %}
<style>
    .table {
        background-color: white;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    
    .table thead {
        background-color: #092b57;
        color: white;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: rgba(0,0,0,.02);
    }
</style>
{% endblock %}

AppWebBA-Django/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
  <link href="{% static 'core/css/home.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <!-- Hero Image -->
  <section class="home-hero">
    <img src="{% static 'core/img/home.jpg' %}" alt="Aires Acondicionados" class="hero-img">
  </section>

  <!-- Título y descripción -->
  <section class="home-title text-center py-4">
    <h1 class="display-4">Aires Acondicionados Buenos Aires</h1>
    <p class="lead">
      En Aires Buenos Aires ofrecemos soluciones de climatización de alta eficiencia para tu hogar y empresa.  
      Más de 20 años de experiencia entregando confort y ahorro energético.
    </p>
  </section>

  <!-- Historia + Botón tienda -->
  <section class="home-info py-5">
    <div class="container">
      <div class="row align-items-center">
        <!-- Columna historia -->
        <div class="col-12 col-md-6 mb-4 mb-md-0">
          <h2>Nuestra Historia</h2>
          <p>
            Fundada en el año 2000, Aires Buenos Aires nació con la misión de llevar el máximo confort 
            a hogares y empresas. Desde nuestros primeros sistemas de aire acondicionado hasta las 
            soluciones innovadoras de hoy, hemos crecido gracias a la confianza de nuestros clientes 
            y al compromiso con la calidad y el servicio.
          </p>
        </div>
        <!-- Columna botón tienda -->
        <div class="col-12 col-md-6 text-center">
          <a href="{% url 'tienda' %}" class="btn btn-primary btn-store btn-lg">
            Visitar Tienda
          </a>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

AppWebBA-Django/core/templates/core/iniciar_pago.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/iniciar_pago.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-6 formulario-pago">
                <h2 class="text-center mb-4">Iniciar Proceso de Pago</h2>
                <form method="POST" action="{{ url_tbk }}">
                    {% csrf_token %}
                    
                    <div class="datos-cliente">
                        <p><strong>Orden de Compra:</strong> {{ buy_order }}</p>
                        <p><strong>Cliente:</strong> {{ first_name }} {{ last_name }}</p>
                        <p><strong>RUT:</strong> {{ rut }}</p>
                        <p><strong>Dirección:</strong> {{ dirusu }}</p>
                        <p><strong>Email:</strong> {{ email }}</p>
                        <p><strong>Monto a Pagar:</strong> ${{ amount }}</p>
                    </div>

                    <input type="hidden" name="token_ws" value="{{ token_ws }}" />
                    <div class="text-center mt-4">
                        <input type="submit" class="btn btn-primary btn-lg" value="Ir a pagar">
                    </div>

                    {% if mesg %}
                    <div id="form_message" class="alert alert-danger mt-3 text-center" role="alert">{{ mesg }}</div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

AppWebBA-Django/core/templates/core/pago_exitoso.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/iniciar_sesion.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% if response_code == 0 %}
        <h1>¡El Pago fue Realizado con Exito!</h1>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-6 borde_formulario text-center">
                    {% csrf_token %}

                    Número de Orden de Compra: {{ buy_order }}<br><br>
                    Nombre cliente: {{ first_name }} {{ last_name }}<br><br>
                    RUT: {{ rut }}<br><br>
                    Dirección: {{ dirusu }}<br><br>
                    Correo electrónico: {{ email }}<br><br>
                    Monto a Pagar: {{ amount }}<br><br>

                    <a href="{% url 'tienda' %}" class="btn btn-info btn-sm">Ir a la tienda</a>
                </div>
            </div>
        </div>
    {% else %}
        <h1>¡El Pago no Pudo ser Realizado con Exito!<br>Por Favor Intente Nuevamente Más Tarde...</h1>
    {% endif %}
{% endblock content %}

AppWebBA-Django/core/templates/core/password_cambiada.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/password_cambiada.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container justify-content-center align-center col-sm-8">
        <h1>¡El cambio de contraseña fue realizado con éxito!</h1>
    </div>
{% endblock content %}